---
- name: "grab git repo" 
  hosts: localhost
  vars_files:
    - ./vars.yml

  tasks:
  - name: Get new source from GIT
    git: 
      repo: "{{ repo }}"
      dest: "./airconnect-docker"
      depth: 1
      accept_hostkey: yes
      clone: yes

 

